package com.example.agentchat.ui.theme

import androidx.compose.ui.graphics.Color

val SkyCreamPrimary = Color(0xFF5A9BD6)
val SkyCreamOnPrimary = Color(0xFFFFFFFF)
val SkyCreamSecondary = Color(0xFFF2B38A)
val SkyCreamOnSecondary = Color(0xFF3D281A)
val SkyCreamBackground = Color(0xFFF7FBFF)
val SkyCreamSurface = Color(0xFFFFFFFF)
val SkyCreamSurfaceVariant = Color(0xFFE6F3FF)
val SkyCreamOnBackground = Color(0xFF243343)
val SkyCreamOnSurface = Color(0xFF243343)
val SkyCreamOnSurfaceVariant = Color(0xFF748899)
val SkyCreamOutline = Color(0xFFC8D9E8)
val SkyCreamError = Color(0xFFD95C62)
val SkyCreamOnError = Color(0xFFFFFFFF)

val NightSkyPrimary = Color(0xFF8CC4F4)
val NightSkyOnPrimary = Color(0xFF102033)
val NightSkySecondary = Color(0xFFF3CFAE)
val NightSkyOnSecondary = Color(0xFF35291D)
val NightSkyBackground = Color(0xFF101A28)
val NightSkySurface = Color(0xFF172538)
val NightSkySurfaceVariant = Color(0xFF223650)
val NightSkyOnBackground = Color(0xFFECF5FC)
val NightSkyOnSurface = Color(0xFFECF5FC)
val NightSkyOnSurfaceVariant = Color(0xFFB4C7D9)
val NightSkyOutline = Color(0xFF3E5873)
val NightSkyError = Color(0xFFFF9A9F)
val NightSkyOnError = Color(0xFF3F1115)
